config/routes.rb
Rails.application.routes.draw do

  match '/search' => 'search#search', via: [:get, :post]
  get '/search/autocomplete' => 'search#autocomplete'

  get '/states'            => 'states#index', as: 'states'
  get '/:id'               => 'states#show', as: 'state'

  get '/:state/counties'     => 'counties#index', as: 'state_counties'
  get '/:state/:id'          => 'counties#show', constraints: { :id => /.+-(county|borough|census-area|parish)/ }, as: 'county'

  get '/:state/cities'         => 'cities#index', as: 'state_cities'
  get '/:state/:id'            => 'cities#show', as: 'city'
  get '/:state/:county/cities' => 'cities#index', constraints: { :county => /.+-(county|borough|census-area|parish)/ }, as: 'county_cities'

  root 'homepage#index'

end

app/models/state.rb
class State < ActiveRecord::Base
  extend FriendlyId
  searchkick settings: {number_of_shards: 1}, text_start: [:auto_complete], text_start: [:state_name]

  friendly_id :name, use: [:slugged, :finders]
  has_many :counties
  has_many :cities
  has_many :description, class_name: StateDescription

  validates_presence_of :name, :state_id, :slug, :latitude, :longitude
  validates :abbreviation, length: { in: 2..3 }	
  validates :fips, length: { is: 5 }
  validates :country, inclusion: { in: %w(US), message: "%{value} is not a valid country code" } 

  before_validation(on: :create) do
    self.fips = self.state_id.to_s.rjust(2, '0') + "000"
  end

  def capital
    City.find_by(state:self, state_capital: 1)
  end

  def active_description
    self.description.find_by(active: true)
  end

  def search_data
    {
      state_name:         self.name,
      state_abbreviation: self.abbreviation,
      auto_complete:      self.decorate.search_display
    }
  end

end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show]

  # GET /states
  def index
    @states = State.all.order(:name)
  end

  # GET /states/1
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id]) rescue nil
      raise ActionController::RoutingError.new('Not Found') if (@state.nil?)
    end

end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abbreviation %><br>
    <%= f.text_field :abbreviation %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br>
    <%= f.text_field :state_id %>
  </div>
  <div class="field">
    <%= f.label :fips %><br>
    <%= f.text_field :fips %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.haml
-if notice.present?
  .row
    .col-md-12
      %p#notice
        = notice
.row#breadcrumb
  .col-md-12
    %ol.breadcrumb
      %li
        =link_to 'Home', '/'
      %li.active
        States
.row
  .col-md-8.col-sm-6
    %h1
      States
    %h2 Description:
.row
  .col-md-12
    %h3
      List of States
    %ul.list_of.states
      -@states.in_groups_of(4, false).each_with_index do |group, index|
        -group.each do |state|
          %li.col-md-3.col-sm-4.col-xs-6
            =link_to state.name, '/' + state.slug

app/views/states/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.haml
-if notice.present?
  .row
    .col-md-12
      %p#notice
        = notice
.row#breadcrumb
  .col-md-12
    %ol.breadcrumb{ 'itemscope' => 'itemscope', 'itemtype' => 'http://schema.org/Breadcrumb' }
      %li
        =link_to 'Home', '/', 'itemprop' => 'url'
      %li.active{ 'itemprop' => 'title' }
        =@state.name
.row
  .col-md-8.col-sm-6
    %h1
      = @state.name
    %ul
      - if (@state.capital.present?)
        %li
          %strong Capital:
          = link_to(@state.capital.name, @state.capital)
      %li
        %strong Abbreviation:
        = @state.abbreviation
      = render partial: '/shared/population', locals: {obj: @state}
      = render partial: '/shared/area', locals: {obj: @state}
      %li
        %strong Counties:
        = link_to("#{number_with_delimiter(@state.counties.count)} Counties", state_counties_path(@state))
      %li
        %strong Cities:
        = link_to("#{number_with_delimiter(@state.cities.count)} Cities", state_cities_path(@state))
    = render partial: '/shared/web_links', locals: {obj: @state}
  .col-md-4.col-sm-6.hidden-xs
    #map_div{ 'data-state' => @state.abbreviation, 'data-center-lat' => @state.latitude, 'data-center-long' => @state.longitude, 'data-center-zoom' => @state.zoom }

.row
  .col-md-12
    %h2 Description:
    = @state.active_description.description rescue '' 