config/routes.rb
Rails.application.routes.draw do

  match '/search' => 'search#search', via: [:get, :post]
  get '/search/autocomplete' => 'search#autocomplete'

  get '/states'            => 'states#index', as: 'states'
  get '/:id'               => 'states#show', as: 'state'

  get '/:state/counties'     => 'counties#index', as: 'state_counties'
  get '/:state/:id'          => 'counties#show', constraints: { :id => /.+-(county|borough|census-area|parish)/ }, as: 'county'

  get '/:state/cities'         => 'cities#index', as: 'state_cities'
  get '/:state/:id'            => 'cities#show', as: 'city'
  get '/:state/:county/cities' => 'cities#index', constraints: { :county => /.+-(county|borough|census-area|parish)/ }, as: 'county_cities'

  root 'homepage#index'

end

app/models/county.rb
class County < ActiveRecord::Base
  extend FriendlyId
  searchkick settings: {number_of_shards: 1}, text_start: [:auto_complete]

  friendly_id :build_slug, use: [:slugged, :finders]
  belongs_to :state
  has_many :cities
  has_many :description, class_name: CountyDescription

  validates_presence_of :name, :county_id, :slug, :state
  validates :county_type, inclusion: { in: ['Borough', 'Census Area', 'County', 'Parish', 'City'], message: "%{value} is not a valid county type" }
  validates :fips, length: { is: 5 }

  before_validation(on: :create) do
    self.fips = self.state.state_id.to_s.rjust(2, '0') + self.county_id.to_s.rjust(3, '0') rescue ''
  end

  def build_slug
    [ [ self.name, self.county_type ] ]
  end

  def normalize_friendly_id(s)
    self.state.slug + '/' + super rescue super
  end

  def capitals
    City.where(county:self).where.not(county_capital: nil).order(:county_capital)
  end

  def active_description
    self.description.find_by(active: true)
  end

  def search_data
    {
      name:            self.name,
      county_type:     self.county_type,
      st_name:         self.state.name,
      st_abbreviation: self.state.abbreviation,
      auto_complete:   self.decorate.search_display
    }
  end

end

app/controllers/counties_controller.rb
class CountiesController < ApplicationController
  before_action :set_county, only: [:show]

  # GET /counties
  def index
    @state = State.find(params[:state]).decorate rescue nil
    @counties = @state.present? ? County.where(state: @state).order(:name).decorate : nil
    raise ActionController::RoutingError.new('Not Found') if (@counties.nil?)
  end

  # GET /counties/1
  def show
    @capitals = @county.capitals
    raise ActionController::RoutingError.new('Not Found') if (@county.nil?)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_county
      @state = State.find(params[:state]).decorate rescue nil
      @county   = County.find(params[:id]).decorate rescue nil
      @county ||= County.find(params[:state] + '/' + params[:id]).decorate rescue nil
      raise ActionController::RoutingError.new('Not Found') if (@county.nil?)
    end

end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/views/counties/_form.html.erb
<%= form_for(@county) do |f| %>
  <% if @county.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@county.errors.count, "error") %> prohibited this county from being saved:</h2>

      <ul>
      <% @county.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :county_type %><br>
    <%= f.text_field :county_type %>
  </div>
  <div class="field">
    <%= f.label :county_id %><br>
    <%= f.number_field :county_id %>
  </div>
  <div class="field">
    <%= f.label :fips %><br>
    <%= f.text_field :fips %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/counties/edit.html.erb
<h1>Editing county</h1>

<%= render 'form' %>

<%= link_to 'Show', @county %> |
<%= link_to 'Back', counties_path %>

app/views/counties/index.html.haml
-if notice.present?
  .row
    .col-md-12
      %p#notice
        = notice
.row#breadcrumb
  .col-md-12
    %ol.breadcrumb
      %li
        =link_to 'Home', '/'
      %li
        =link_to @state.display_name, @state
      %li.active
        Counties
.row
  .col-md-8.col-sm-6
    %h1 
      = 'Counties in ' + @state.display_name
    %h2 Description:
    = @state.active_description.description rescue ''
  .col-md-4.col-sm-6.hidden-xs
    #map_div{ 'data-state' => @state.abbreviation, 'data-center-lat' => @state.latitude, 'data-center-long' => @state.longitude, 'data-center-zoom' => @state.zoom }
.row
  .col-md-12
    %h3 
      List of Counties
    %ul.list_of.counties
      -@counties.in_groups_of(4, false).each_with_index do |group, index|
        -group.each do |county|
          .col-md-3.col-sm-4.col-xs-6
            =link_to county.display_name, county

app/views/counties/new.html.erb
<h1>New county</h1>

<%= render 'form' %>

<%= link_to 'Back', counties_path %>

app/views/counties/show.html.haml
-if notice.present?
  .row
    .col-md-12
      %p#notice
        = notice
.row#breadcrumb
  .col-md-12
    %ol.breadcrumb
      %li
        =link_to 'Home', '/'
      %li
        =link_to @county.state.decorate.display_name, @county.state
      %li.active
        =@county.display_name
.row
  .col-md-8.col-sm-6
    %h1
      = @county.display_name
    %ul
      %li
        %strong State:
        = link_to @county.state.decorate.display_name, @county.state
      - if @capitals.length > 0
        %li
          %strong
            = "#{@county.county_type} #{'Seat'.pluralize(@capitals.length)}:"
          - @capitals.each_with_index do |city, index|
            = (link_to(city.decorate.display_name, city) + (index < (@capitals.length - 1) ? ', ' : '')).html_safe
      = render partial: '/shared/population', locals: {obj: @county}
      = render partial: '/shared/area', locals: {obj: @county}
      %li
        %strong Cities:
        = link_to("#{number_with_delimiter(@county.cities.count)} Cities", county_cities_path(county: @county))
    = render partial: '/shared/web_links', locals: {obj: @county}
  .col-md-4.col-sm-6.hidden-xs
    #map_div{ 'data-state' => @county.state.abbreviation, 'data-county' => @county.name, 'data-center-lat' => @county.state.latitude, 'data-center-long' => @county.state.longitude, 'data-center-zoom' => @county.state.zoom }

.row
  .col-md-12
    %h2 Description:
    = @county.active_description.description rescue ''