config/routes.rb
Rails.application.routes.draw do

  match '/search' => 'search#search', via: [:get, :post]
  get '/search/autocomplete' => 'search#autocomplete'

  get '/states'            => 'states#index', as: 'states'
  get '/:id'               => 'states#show', as: 'state'

  get '/:state/counties'     => 'counties#index', as: 'state_counties'
  get '/:state/:id'          => 'counties#show', constraints: { :id => /.+-(county|borough|census-area|parish)/ }, as: 'county'

  get '/:state/cities'         => 'cities#index', as: 'state_cities'
  get '/:state/:id'            => 'cities#show', as: 'city'
  get '/:state/:county/cities' => 'cities#index', constraints: { :county => /.+-(county|borough|census-area|parish)/ }, as: 'county_cities'

  root 'homepage#index'

end

app/models/city.rb
class City < ActiveRecord::Base
  extend FriendlyId
  searchkick settings: {number_of_shards: 1}, text_start: [:auto_complete]

  friendly_id :build_slug, use: [:slugged, :finders]
  belongs_to :state
  belongs_to :county
  has_many :description, class_name: CityDescription

  validates_presence_of :name, :gnis, :slug, :county, :state
  validates :fips, length: { is: 5 }

  before_validation(on: :create) do
    self.fips = self.county.fips rescue ''
  end

  def build_slug
    [ self.name ]
  end

  def normalize_friendly_id(s)
    self.state.slug + '/' + super rescue super
  end

  def active_description
    self.description.find_by(active: true)
  end

  def search_data
    {
      name:            self.name,
      st_name:         self.state.name,
      st_abbreviation: self.state.abbreviation,
      auto_complete:   self.decorate.search_display
    }
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show]

  # GET /cities
  def index
    @state = State.find(params[:state]).decorate rescue nil
    @county = County.find(params[:state] + '/' + params[:county]).decorate rescue nil if (params[:county].present?)
    @cities = @county.present? ? @county.cities.order(:name) : nil
    @cities ||= @state.present? ? @state.cities.order(:name).decorate : nil
    raise ActionController::RoutingError.new('Not Found') if (@cities.nil?)
  end

  # GET /cities/1
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @state = State.find(params[:state]).decorate rescue nil
      @city = City.find(params[:state] + '/' + params[:id]).decorate rescue nil
      raise ActionController::RoutingError.new('Not Found') if (@city.nil?)
    end

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/index.html.haml
-if notice.present?
  .row
    .col-md-12
      %p#notice
        = notice
.row#breadcrumb
  .col-md-12
    %ol.breadcrumb
      %li
        =link_to 'Home', '/'
      %li
        =link_to @state.display_name, @state
      - if (@county.present?)
        %li
          =link_to @county.display_name, @county
      %li.active
        Cities
.row
  .col-md-8.col-sm-6
    %h1 
      = 'Cities in ' + (@county.present? ? @county.display_name + ', ' : "") + @state.display_name
    %h2 Description:
    = @state.active_description.description rescue ''
  .col-md-4.col-sm-6.hidden-xs
    #map_div{ 'data-state' => @state.abbreviation, 'data-center-lat' => @state.latitude, 'data-center-long' => @state.longitude, 'data-center-zoom' => @state.zoom }
.row
  .col-md-12
    %h3 
      List of Cities
    %ul.list_of.cities
      -@cities.in_groups_of(4, false).each_with_index do |group, index|
        -group.each do |city|
          %li.col-md-3.col-sm-4.col-xs-6
            =link_to city.decorate.display_name, city
            =city.decorate.display_capital_info

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.haml
-if notice.present?
  .row
    .col-md-12
      %p#notice
        = notice
.row#breadcrumb
  .col-md-12
    %ol.breadcrumb
      %li{ 'itemscope' => 'itemscope', 'itemtype' => 'http://schema.org/Breadcrumb' }
        =link_to 'Home', '/', 'itemprop' => 'url'
      %li{ 'itemscope' => 'itemscope', 'itemtype' => 'http://schema.org/Breadcrumb' }
        =link_to @city.state.decorate.display_name, @city.state, 'itemprop' => 'url'
      %li.active{ 'itemscope' => 'itemscope', 'itemtype' => 'http://schema.org/Breadcrumb' }
        %span{ 'itemprop' => 'title' }
          =@city.display_name
.row
  .col-md-8.col-sm-6{ 'itemscope' => 'itemscope', 'itemtype' => 'http://schema.org/City' }
    %h1{ 'itemprop' => 'name' }
      = @city.display_name
    %ul
      %li
        %strong State:
        = link_to @city.state.decorate.display_name, @city.state, 'itemprop' => 'containedIn'
        - if (@city.state_capital.present?)
          (State capital)
      %li
        %strong Primary County:
        = link_to @city.county.decorate.display_name, @city.county, 'itemprop' => 'containedIn'
        - if (@city.county_capital.present?)
          (County capital)
      = render partial: '/shared/population', locals: {obj: @city}
      = render partial: '/shared/area', locals: {obj: @city}
    = render partial: '/shared/web_links', locals: {obj: @city}
  .col-md-4.col-sm-6.hidden-xs
    #map_div{ 'data-city-lat' => @city.latitude, 'data-city-long' => @city.longitude, 'data-state' => @city.state.abbreviation, 'data-city' => @city.name, 'data-center-lat' => @city.state.latitude, 'data-center-long' => @city.state.longitude, 'data-center-zoom' => @city.state.zoom }

.row
  .col-md-12
    %h2{ 'itemprop' => 'description' } Description:
    = @city.active_description.description rescue ''